//
//  AlbumsViewController.swift
//  Viper
//
//  Created by Victor Alejandria on 30/08/2019.
//  Copyright (c) 2019 Victor Alejandria. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift

final class AlbumsViewController: UIViewController {
	
	// MARK: - Public properties -
	var presenter: AlbumsPresenterInterface!
	
	// MARK: - Private properties -
	@IBOutlet private weak var name: UILabel!
	@IBOutlet private weak var username: UILabel!
	@IBOutlet private weak var email: UILabel!
	@IBOutlet private weak var address: UILabel!
	@IBOutlet private weak var phone: UILabel!
	@IBOutlet private weak var website: UILabel!
	@IBOutlet private weak var tableView: UITableView!
	private let disposeBag = DisposeBag()
	
	// MARK: - Lifecycle -
	override func viewDidLoad() {
		super.viewDidLoad()
		
		presenter.setupLabels()
		presenter.showUserAlbums { [unowned self] (albums) -> (Void) in
			self.setupTableViewCell()
			self.setupTableViewTap()
			self.tableView.reloadData()
		}
	}
	
	@IBAction func changeButtonTap(_ sender: Any) {
		presenter.changeUserInfo()
	}
	
	func setupTableViewCell() {
		presenter.albums.bind(to: tableView
			.rx
			.items(cellIdentifier: "albumCell")) {
				row, item, cell in
				cell.textLabel?.text = item.title
		}
		.disposed(by: disposeBag)
	}
	
	func setupTableViewTap() {
		tableView.rx
			.modelSelected(Album.self)
			.subscribe ({ [unowned self] (user) in
				let selectedAlbum = self.presenter.albums.value[self.tableView.indexPathForSelectedRow?.item ?? 0]
				self.showSelectedAlbumWith(album: selectedAlbum)
			}).disposed(by: disposeBag)
	}
}

// MARK: - Extensions -

extension AlbumsViewController: AlbumsViewInterface {
	func setupLabelsWith(user: User) {
		self.name.text = user.name
		self.username.text = user.username
		self.email.text = user.email
		self.address.text = user.address
		self.phone.text = user.phone
		self.website.text = user.website
	}
	
	func showSelectedAlbumWith(album: Album) {
		presenter.show(album: album)
	}
}
