//
//  AlbumsViewController.swift
//  Viper
//
//  Created by Victor Alejandria on 30/08/2019.
//  Copyright (c) 2019 Victor Alejandria. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class AlbumsViewController: UIViewController {

    // MARK: - Public properties -

	@IBOutlet private weak var name: UILabel!
	@IBOutlet private weak var username: UILabel!
	@IBOutlet private weak var email: UILabel!
	@IBOutlet private weak var address: UILabel!
	@IBOutlet private weak var phone: UILabel!
	@IBOutlet private weak var website: UILabel!
	@IBOutlet private weak var tableview: UITableView!

	var presenter: AlbumsPresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()

		name.text = presenter.user.name
		username.text = presenter.user.username
		email.text = presenter.user.email
		address.text = presenter.user.address
		phone.text = presenter.user.phone
		website.text = presenter.user.website

    }
	
}

// MARK: - Extensions -

extension AlbumsViewController: AlbumsViewInterface {
}
