//
//  AlbumsInterfaces.swift
//  Viper
//
//  Created by Victor Alejandria on 30/08/2019.
//  Copyright (c) 2019 Victor Alejandria. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol AlbumsWireframeInterface: WireframeInterface {
}

protocol AlbumsViewInterface: ViewInterface {
}

protocol AlbumsPresenterInterface: PresenterInterface {
	var user: User { get }
	var albums: [Album] { get }
}

protocol AlbumsInteractorInterface: InteractorInterface {
}
