//
//  AlbumsViewController.swift
//  Viper
//
//  Created by Victor Alejandria on 30/08/2019.
//  Copyright (c) 2019 Victor Alejandria. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

final class AlbumsViewController: UIViewController {
	
	// MARK: - Public properties -
	var presenter: AlbumsPresenterInterface!
	
	// MARK: - Private properties -
	@IBOutlet private weak var name: UILabel!
	@IBOutlet private weak var username: UILabel!
	@IBOutlet private weak var email: UILabel!
	@IBOutlet private weak var address: UILabel!
	@IBOutlet private weak var phone: UILabel!
	@IBOutlet private weak var website: UILabel!
	@IBOutlet private weak var tableView: UITableView!
	private let disposeBag = DisposeBag()

	// MARK: - Lifecycle -

	override func viewDidLoad() {
		super.viewDidLoad()

		self.setupTableViewTap()
	}

	override func viewWillAppear(_ animated: Bool) {
		super.viewWillAppear(animated)

		setupLabels()
		presenter.showUserAlbums { [unowned self] (albums) -> (Void) in
			self.tableView.delegate = nil
			self.tableView.dataSource = nil
			self.setupTableViewCell()
			self.tableView.reloadData()
		}
	}

	@IBAction func changeButtonTap(_ sender: Any) {
		presenter.changeUser()
	}
	
	func setupTableViewCell() {
		presenter.albums.bind(to: tableView
			.rx
			.items(cellIdentifier: "albumCell")) {
				row, item, cell in
				cell.textLabel?.text = item.title
		}
		.disposed(by: disposeBag)
	}
	
	func setupTableViewTap() {
		tableView.rx
			.modelSelected(Album.self)
			.subscribe ({ [unowned self] (user) in
				let selectedAlbum = self.presenter.albums.value[self.tableView.indexPathForSelectedRow?.item ?? 0]
				self.showSelectedAlbumWith(album: selectedAlbum)
			}).disposed(by: disposeBag)
	}
}

// MARK: - Extensions -

extension AlbumsViewController: AlbumsViewInterface {
	func setupLabels() {
		presenter.user.asObservable().bind {
			self.name.text = $0.name
			self.username.text = $0.username
			self.email.text = $0.email
			self.address.text = $0.address
			self.phone.text = $0.phone
			self.website.text = $0.website
		}.disposed(by: disposeBag)
	}
	
	func showSelectedAlbumWith(album: Album) {
		presenter.show(album: album)
	}
}
