//
//  AlbumsInteractor.swift
//  Viper
//
//  Created by Victor Alejandria on 30/08/2019.
//  Copyright (c) 2019 Victor Alejandria. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class AlbumsInteractor {
}

// MARK: - Extensions -

extension AlbumsInteractor: AlbumsInteractorInterface {
	func getAlbumBy(id: Int, completion: @escaping AlbumCompletionBlock) {
		Services.getAlbumBy(id: id, completion: completion)
	}

	func getAlbumsBy(user: Int, completion: @escaping AlbumsCompletionBlock) {
		Services.getAlbumsBy(user: user, completion: completion)
	}

}
