//
//  PhotosInteractor.swift
//  Viper
//
//  Created by Victor Alejandria on 30/08/2019.
//  Copyright (c) 2019 Victor Alejandria. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class PhotosInteractor {
}

// MARK: - Extensions -

extension PhotosInteractor: PhotosInteractorInterface {
}
