//
//  PhotosInterfaces.swift
//  Viper
//
//  Created by Victor Alejandria on 30/08/2019.
//  Copyright (c) 2019 Victor Alejandria. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol PhotosWireframeInterface: WireframeInterface {
	func willPresentAlbum(id: Int)
}

protocol PhotosViewInterface: ViewInterface {
	func presentAlbumActionWith(id: Int)
}

protocol PhotosPresenterInterface: PresenterInterface {
	func showAlbumWith(Id: Int)
}

protocol PhotosInteractorInterface: InteractorInterface {
}
