//
//  PhotosInterfaces.swift
//  Viper
//
//  Created by Victor Alejandria on 30/08/2019.
//  Copyright (c) 2019 Victor Alejandria. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

typealias PhotosCompletionBlock = ([Photo]) -> (Void)
typealias PhotoCompletionBlock = (Photo) -> (Void)

protocol PhotosWireframeInterface: WireframeInterface {
}

protocol PhotosViewInterface: ViewInterface {
	func showPhotos()
}

protocol PhotosPresenterInterface: PresenterInterface {
	var album: BehaviorRelay<Album> { get }
	var photos: BehaviorRelay<[Photo]> { get }
	var localImageCache: BehaviorRelay<NSCache<NSString, UIImage>> { get }

	func showPhotosWithAlbum(id: Int, completion: @escaping PhotosCompletionBlock)
    func downloadPhotoWith(url: String, completion: @escaping DownloadedImageCompletionBlock)
}

protocol PhotosInteractorInterface: InteractorInterface {
    func downloadPhotoWith(url: String, completion: @escaping DownloadedImageCompletionBlock)
	func getPhotosWithAlbum(id: Int, completion: @escaping PhotosCompletionBlock)
}
