//
//  PhotosInteractor.swift
//  Viper
//
//  Created by Victor Alejandria on 30/08/2019.
//  Copyright (c) 2019 Victor Alejandria. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import RxSwift

final class PhotosInteractor {

    private var privateService: APIServicesInterfaces!
	private let disposeBag = DisposeBag()

}

// MARK: - Extensions -

extension PhotosInteractor: PhotosInteractorInterface {
    func downloadPhotoWith(url: String, completion: @escaping DownloadedImageCompletionBlock) {
		self.services.downloadImageDataFrom(url: url).drive(onNext: { (data) in
			completion(data)
		}).disposed(by: disposeBag)
	}

    var services: APIServicesInterfaces {
        get {
            return privateService
        }
        set {
            privateService = newValue
        }
    }

    convenience init(services: APIServicesInterfaces) {
        self.init()

        self.services = services
    }

	func getPhotosWithAlbum(id: Int, completion: @escaping PhotosCompletionBlock) {
		services.getPhotosBy(album: id).drive(onNext: { (photos) in
			completion(photos)
		}).disposed(by: disposeBag)
	}
}
