//
//  PhotosPresenter.swift
//  Viper
//
//  Created by Victor Alejandria on 30/08/2019.
//  Copyright (c) 2019 Victor Alejandria. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class PhotosPresenter {

    // MARK: - Private properties -

    private unowned let view: PhotosViewInterface
    private let interactor: PhotosInteractorInterface
    private let wireframe: PhotosWireframeInterface

    // MARK: - Lifecycle -

    init(view: PhotosViewInterface, interactor: PhotosInteractorInterface, wireframe: PhotosWireframeInterface) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension PhotosPresenter: PhotosPresenterInterface {
	func showAlbumWith(Id: Int) {
		wireframe.willPresentAlbum(id: Id)
	}
	

}
