//
//  PhotosViewController.swift
//  Viper
//
//  Created by Victor Alejandria on 30/08/2019.
//  Copyright (c) 2019 Victor Alejandria. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class PhotosViewController: UIViewController {

    // MARK: - Public properties -

	@IBOutlet weak var jumpButton: UIButton!
	var presenter: PhotosPresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
    }
	
	@IBAction func jumpButtonTapped(_ sender: Any) {
		presentAlbumActionWith(id: 1)
	}
}

// MARK: - Extensions -

extension PhotosViewController: PhotosViewInterface {
	func presentAlbumActionWith(id: Int) {
		presenter.showAlbumWith(Id: id)
	}

}
