//
//  ChangeUserInterfaces.swift
//  Viper
//
//  Created by Victor Alejandria on 12/09/2019.
//  Copyright (c) 2019 Victor Alejandria. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

enum ChangeUser {

    struct ViewOutput {
    }

    struct ViewInput {
    }

}

protocol ChangeUserWireframeInterface: WireframeInterface {
}

protocol ChangeUserViewInterface: ViewInterface {
}

protocol ChangeUserPresenterInterface: PresenterInterface {
	var user: BehaviorRelay<User> { get }

    func configure(with output: ChangeUser.ViewOutput) -> ChangeUser.ViewInput
}

protocol ChangeUserInteractorInterface: InteractorInterface {
}
