//
//  ChangeUserViewController.swift
//  Viper
//
//  Created by Victor Alejandria on 12/09/2019.
//  Copyright (c) 2019 Victor Alejandria. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

final class ChangeUserViewController: UIViewController {

    // MARK: - Public properties -

    var presenter: ChangeUserPresenterInterface!

    // MARK: - Private properties -

    private let disposeBag = DisposeBag()

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        configure()
    }
	
}

// MARK: - Extensions -

extension ChangeUserViewController: ChangeUserViewInterface {
}

private extension ChangeUserViewController {

    func configure() {
        let output = ChangeUser.ViewOutput()

        let input = presenter.configure(with: output)
    }

}
