//
//  ChangeUserPresenter.swift
//  Viper
//
//  Created by Victor Alejandria on 12/09/2019.
//  Copyright (c) 2019 Victor Alejandria. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import RxSwift
import RxCocoa

final class ChangeUserPresenter {

    // MARK: - Private properties -

    private unowned let view: ChangeUserViewInterface
    private let interactor: ChangeUserInteractorInterface
    private let wireframe: ChangeUserWireframeInterface
	private let privateUser: BehaviorRelay<User>

    // MARK: - Lifecycle -

	init(view: ChangeUserViewInterface, interactor: ChangeUserInteractorInterface, wireframe: ChangeUserWireframeInterface, user: BehaviorRelay<User>) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
		self.privateUser = user
    }
}

// MARK: - Extensions -

extension ChangeUserPresenter: ChangeUserPresenterInterface {
	var user: BehaviorRelay<User> {
		return privateUser
	}

    func configure(with output: ChangeUser.ViewOutput) -> ChangeUser.ViewInput {
        return ChangeUser.ViewInput()
    }
}
