//
//  ChangeUserWireframe.swift
//  Viper
//
//  Created by Victor Alejandria on 12/09/2019.
//  Copyright (c) 2019 Victor Alejandria. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

final class ChangeUserWireframe: BaseWireframe<ChangeUserViewController> {

    // MARK: - Private properties -

    private let storyboard = UIStoryboard(name: "ChangeUser", bundle: nil)

    // MARK: - Module setup -

	init(user: BehaviorRelay<User>) {
        let moduleViewController = storyboard.instantiateViewController(ofType: ChangeUserViewController.self)
        super.init(viewController: moduleViewController)
        
        let interactor = ChangeUserInteractor()
        let presenter = ChangeUserPresenter(view: moduleViewController, interactor: interactor, wireframe: self, user: user)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension ChangeUserWireframe: ChangeUserWireframeInterface {
}
