//
//  ChangeUserInteractor.swift
//  Viper
//
//  Created by Victor Alejandria on 12/09/2019.
//  Copyright (c) 2019 Victor Alejandria. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import RxSwift

final class ChangeUserInteractor {
}

// MARK: - Extensions -

extension ChangeUserInteractor: ChangeUserInteractorInterface {
    var services: APIServicesInterfaces {
        get {
			fatalError()
        }
        set {
			fatalError()
        }
    }
    
    convenience init(services: APIServicesInterfaces) {
        fatalError()
    }
    
}
