//
//  UsersViewController.swift
//  Viper
//
//  Created by Victor Alejandria on 30/08/2019.
//  Copyright (c) 2019 Victor Alejandria. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class UsersViewController: UIViewController {

    // MARK: - Public properties -

	@IBOutlet weak var tableView: UITableView!
	var presenter: UsersPresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()

		showUsers()
    }
	
}

extension UsersViewController: UITableViewDelegate {
	func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
		showUser(index: indexPath.row)
	}
}

extension UsersViewController: UITableViewDataSource {
	func numberOfSections(in tableView: UITableView) -> Int {
		return 1
	}

	func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
		return presenter.users.count
	}

	func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
		let item = presenter.users[indexPath.row]
		var cell = tableView.dequeueReusableCell(withIdentifier: "userCell")
		if (cell == nil)
		{
			cell = UITableViewCell(style: UITableViewCell.CellStyle.subtitle, reuseIdentifier: "userCell")
		}
		cell?.textLabel?.text = item.name
		cell?.detailTextLabel?.text = item.username
		return cell ?? UITableViewCell()
	}
}

// MARK: - Extensions -

extension UsersViewController: UsersViewInterface {
	func showUsers() {
		presenter.showUsers { (users) -> (Void) in
			DispatchQueue.main.async { [weak self] in
				self?.tableView.reloadData()
			}
		}
	}

	func showUser(index: Int) {
		presenter.showUserWith(index: index)
	}

}
