//
//  UsersWireframe.swift
//  Viper
//
//  Created by Victor Alejandria on 30/08/2019.
//  Copyright (c) 2019 Victor Alejandria. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class UsersWireframe: BaseWireframe<UsersViewController> {

    // MARK: - Private properties -

    private let storyboard = UIStoryboard(name: "Users", bundle: nil)

    // MARK: - Module setup -

    init() {
        let moduleViewController = storyboard.instantiateViewController(ofType: UsersViewController.self)
        super.init(viewController: moduleViewController)
        
        let interactor = UsersInteractor(services: Services())
        let presenter = UsersPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension UsersWireframe: UsersWireframeInterface {
	func willShow(user: ServicesUser) {
		navigationController?.pushWireframe(AlbumsWireframe(user: user))
	}
}
