//
//  UsersInteractor.swift
//  Viper
//
//  Created by Victor Alejandria on 30/08/2019.
//  Copyright (c) 2019 Victor Alejandria. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class UsersInteractor {
}

// MARK: - Extensions -

extension UsersInteractor: UsersInteractorInterface {
	func getUsers(completion: @escaping UsersCompletionBlock) {
		Services.getUsers(completion: completion)
	}

	func getUserBy(id: Int, completion: @escaping UserCompletionBlock) {
		Services.getUsersBy(id: id, completion: completion)
	}

}
