//
//  UsersInterfaces.swift
//  Viper
//
//  Created by Victor Alejandria on 30/08/2019.
//  Copyright (c) 2019 Victor Alejandria. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

typealias UsersCompletionBlock = ([ServicesUser]) -> (Void)
typealias UserCompletionBlock = (ServicesUser) -> (Void)


protocol UsersWireframeInterface: WireframeInterface {
	func willShow(user: ServicesUser)
}

protocol UsersViewInterface: ViewInterface {
	func showUsers()
	func showUser(index: Int)
}

protocol UsersPresenterInterface: PresenterInterface {
	var users: [ServicesUser] { get }

	func showUsers(completion: @escaping UsersCompletionBlock)
	func showUserWith(index: Int)
}

protocol UsersInteractorInterface: InteractorInterface {
	func getUsers(completion: @escaping UsersCompletionBlock)
	func getUserBy(id: Int, completion: @escaping UserCompletionBlock)
}
