//
//  UsersInteractor.swift
//  Viper
//
//  Created by Victor Alejandria on 30/08/2019.
//  Copyright (c) 2019 Victor Alejandria. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import RxSwift
import RxCocoa

final class UsersInteractor {

    private var privateService: APIServicesInterfaces!
	private let disposeBag = DisposeBag()

}

// MARK: - Extensions -

extension UsersInteractor: UsersInteractorInterface {
    var services: APIServicesInterfaces {
        get {
            return privateService
        }
        set {
            privateService = newValue
        }
    }

    convenience init(services: APIServicesInterfaces) {
        self.init()
        
        self.services = services
    }

	func getUsers() -> Driver<[ServicesUser]> {
		return services.getUsers()
	}

	func getUserBy(id: Int) -> Driver<ServicesUser> {
		return services.getUsersBy(id: id)
	}

}
