//
//  UsersInterfaces.swift
//  Viper
//
//  Created by Victor Alejandria on 30/08/2019.
//  Copyright (c) 2019 Victor Alejandria. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

protocol UsersWireframeInterface: WireframeInterface {
	func willShow(user: ServicesUser)
}

protocol UsersViewInterface: ViewInterface {
	func showUsers()
	func showUser(index: Int)
}

protocol UsersPresenterInterface: PresenterInterface {
	var users: BehaviorRelay<[ServicesUser]> { get }
	
	func showUsers()
	func showUserWith(index: Int)
}

protocol UsersInteractorInterface: InteractorInterface {
	func getUsers() -> Driver<[ServicesUser]>
	func getUserBy(id: Int) -> Driver<ServicesUser>
}
