//
//  UsersInteractor.swift
//  Viper
//
//  Created by Victor Alejandria on 30/08/2019.
//  Copyright (c) 2019 Victor Alejandria. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class UsersInteractor {

    private var privateService: APIServicesInterfaces!

}

// MARK: - Extensions -

extension UsersInteractor: UsersInteractorInterface {
    var services: APIServicesInterfaces {
        get {
            return privateService
        }
        set {
            privateService = newValue
        }
    }

    convenience init(services: APIServicesInterfaces) {
        self.init()
        
        self.services = services
    }

	func getUsers(completion: @escaping UsersCompletionBlock) {
		services.getUsers(completion: completion)
	}

	func getUserBy(id: Int, completion: @escaping UserCompletionBlock) {
		services.getUsersBy(id: id, completion: completion)
	}

}
